# _common/latexmkrc
$pdf_mode = 4;
$bibtex_use = 2;
$clean_ext = "aux bbl bcf blg fdb_latexmk fls log out run.xml synctex.gz toc";
$lualatex = 'lualatex --synctex=1 -interaction=nonstopmode -file-line-error %O %S';
